---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    pipeline_id: "$GITHUB_RUN_NUMBER"
    build_id: "$GITHUB_RUN_ID"
    environment: $CI_ENVIRONMENT_SLUG
  annotations:
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress-class: 'nginx'
spec:
  tls:
  - hosts:
    - $CI_ENVIRONMENT_HOSTNAME
    secretName: $CI_ENVIRONMENT_SLUG-tls
  rules:
  - host: $CI_ENVIRONMENT_HOSTNAME
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-$CI_ENVIRONMENT_SLUG
            port: 
              number: $PORT