apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    app: $CI_ENVIRONMENT_SLUG
    environment: $CI_ENVIRONMENT_SLUG
    pipeline_id: "$CI_PIPELINE_ID"
    build_id: "$GITHUB_RUN_ID"
spec:
  minAvailable: $PDB_MIN
  selector:
    matchLabels:
      app: $CI_ENVIRONMENT_SLUG