---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{PREFIX}}-$CI_ENVIRONMENT_SLUG
    environment: $CI_ENVIRONMENT_SLUG
  name: {{PREFIX}}-$CI_ENVIRONMENT_SLUG
  namespace: $KUBE_NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{PREFIX}}-$CI_ENVIRONMENT_SLUG
  minReplicas: ${{PREFIX}}_SCALE_MIN
  maxReplicas: ${{PREFIX}}_SCALE_MAX
  targetCPUUtilizationPercentage:  ${{PREFIX}}_SCALE_CPU
